//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane
    {
        public int IdPlan { get; set; }
        public string NombrePlan { get; set; }
        public string Decripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
